name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build da imagem
        run: |
          docker build -t $DOCKER_USERNAME/learn.io:latest .

      - name: Run container (teste com env)
        run: |
          docker run -d \
            -p 3000:3000 \
            -e DATABASE_USER=${{ secrets.DATABASE_USER }} \
            -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
            -e DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
            -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            -e DATABASE_PORT=${{ secrets.DATABASE_PORT }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --name app-test \
            $DOCKER_USERNAME/learn.io:latest

      - name: Aguarda container subir
        run: sleep 10

      - name: Logs do container
        run: docker logs app-test

      - name: Stop container
        run: docker stop app-test

      - name: Push da imagem
        run: |
          docker push $DOCKER_USERNAME/learn.io:latest